name: Github Pages Deploy

on:
   push:
       branches:
           - "main"

jobs :
    build:
        runs-on: window-latest


strategy:
  matrix:
   node-version: [15.x]


   steps:
   - name: Checkout
   uses: actions/checkout@y1

   - name: Install and build
   run: npm install && npm run build

   - name: Deploy
    uses: vivek1209-star-blog/github-pages-deploy-action@4.1.1
    with:
         branch: gh-pages
         folder: build           